# Generated by Django 5.1.6 on 2025-03-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', 'create_default_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramchannel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
